### ISSUE TITLE
How to get the statistics?

### ISSUE THREAD

**Issue by TiankaiHang** [byeonghu-na/INDM#1]
Hi,

Thanks for your nice work!!
May I ask how you build the `celeba_stats.npz` file? Crop it to 140x140 then resize it to 64x64 with tf?

Best.

**Comment by Kim-Dongjun** [comment]
That's right. We followed the preprocessing step to process the real data, according to Yang Song's original work.
Note that clean-FID resizes this 64x64 real data to 299x299 resolution before putting it into the inception network.
